### ISSUE TITLE
Handle "no config" errors and guide the user appropriately

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#100]
If a sync is attempted with no config it is likely there will be no good outcome, particularly for WordPress multisite. We should detect when a sync is attempted with no config, and direct the user to documentation to create some (for now, ideally we'd be much more helpful).

**Comment by joshbetz** [comment]
I think we should detect this in the API and error there. We'd likely want the same functionality in the Dashboard and any custom tools.

**Comment by simonwheatley** [comment]
> I think we should detect this in the API and error there.

Agreed. Do you mean the public API or the container orchestration API? On the assumption it's the former, I've added an issue there.

https://github.com/Automattic/vip-go-api-public/issues/85

Renaming this issue to make it clearer.

**Comment by mjangda** [comment]
Related: #115 (we're not correctly surfacing errors)
