### ISSUE TITLE
Add more verbose logging for import/export commands

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-cli#105]
Right now we only show a progress bar, but debugging is hard if something fails. We could output a log to a file or add a `--verbose` option, which outputs filenames along with current progress to stdout.

For example:

```
(1/1000) /path/to/file.jpg
(2/1000) /path/to/file2.jpg
...
```

**Comment by mjangda** [comment]
It would also be nice to get separate outputs of files that were skipped.
