### ISSUE TITLE
Sync: incorrect error on failure

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-cli#115]
We show a generic error on all failures:

```
Note: Someone recently ran a data sync on this site
Note: Please wait a few minutes before trying again
```

This is a lie. We should show the correct error message.

**Comment by joshbetz** [comment]
The problem is that we don't return enough information in GraphQL about the failed request to GOOP. We only get 'Bad Request' or 'Conflict'. We'll resolve this in https://github.com/Automattic/vip-go-api-public/pull/114.
