### ISSUE TITLE
Pagination for the app list

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#116]
Currently we only show the first page of 10 apps for `vip app list`, we should allow pagination to show more (and maybe increase the page size).

**Comment by joshbetz** [comment]
I'm not sure if this is directly related to data sync?

**Comment by simonwheatley** [comment]
I did muse a little before adding it to that project board (project board is private, for anyone following along, sorry), figuring that someone would push back if appropriate. (We need to review that board soon, it’s got way too many unprioritised issues on it.)

The issue as it relates to data sync is that some clients have more applications than they can see, so they find data sync partially inaccessible.

**Comment by joshbetz** [comment]
I would like to loop over all pages and automatically pipe to `less` like `git log`, but I think we need to find out how that works on Windows first.
