### ISSUE TITLE
Docker issues on Mac (intel) version > 2.17.0

### ISSUE THREAD

**Issue by wpdigitalsilk** [Automattic/vip-cli#1168]
## Expected/Desired Behavior

Fill with either one:

running any `vip dev-env` command will result with error:

Error:  Failed to connect to docker. Please verify that the current user is part of docker group and has access to docker commands.

## Steps to Reproduce the Problem

1. `vip dev-env list`
1. or `vip dev-env destroy` 

## (Optional) Additional notes

Running validation steps...
✓ Check for docker installation 
✓ Check for docker-compose installation 
⠙ Check access to docker for current user 
○ Check DNS resolution 
Error:  Failed to connect to docker. Please verify that the current user is part of docker group and has access to docker commands.
Debug:  VIP-CLI v2.22.0, Node v14.20.0, darwin 21.6.0

**Comment by priscillamc** [comment]
I just ran into this issue as well updating to 2.23.0 on Mac (intel) Monterey 12.6.1. 
Debug:  VIP-CLI v2.23.0, Node v18.12.0, darwin 21.6.0

It's working now after updating Docker to 4.13.1 and then installing XCode Command Line Tools and python (via Homebrew).

```
xcode-select --install

brew install python
```
