### ISSUE TITLE
Development environment SQL import fails

### ISSUE THREAD

**Issue by rbackert** [Automattic/vip-cli#1192]
## Expected/Desired Behavior

Importing sql files into a local development environment [as documented](https://docs.wpvip.com/how-tos/dev-env-add-content/) succeeds.

## Actual Behavior

Importing sql files into a local development environment fails.

## Steps to Reproduce the Problem

1. Place a sql file at `$HOME/db.sql`
2. Run `vip dev-env --slug=project-slug import sql ~/db.sql`
3. See error: `Import file missing or not readable: /user/db.sql`

## Additional notes

`$HOME`is no longer mounted into `/user` as per https://github.com/Automattic/vip-cli/blob/develop/src/lib/dev-environment/dev-environment-lando.js#L68, `dev-env import sql` expects the files to be available at `/user` in the container.

**Comment by sjinks** [comment]
Fixed in 2.24.1.
