### ISSUE TITLE
logout command gives no feedback

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#129]
We should have some kind of confirmation message when the `vip logout` command is run and succeeds; currently I see:

``` shell
SWTBMBP:Desktop simonwheatley$ vip logout
SWTBMBP:Desktop simonwheatley$
```

**Comment by joshbetz** [comment]
Originally I was using the unix philosophy that no output means success, but maybe we don't want that.

**Comment by simonwheatley** [comment]
🤔

**Comment by mjangda** [comment]
I think the unix philosophy optimizes for the computer experience but not as much for the human experience. I think we should optimize more for humans side and still be friendly towards scripted usage, where possible.
