### ISSUE TITLE
vip app list: Don't pipe to $PAGER if no apps found

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-cli#145]

**Comment by joshbetz** [comment]
Is there a specific problem with sending the empty table through `less`? We should be able to do this, but it should exit immediately if there's less than 1 terminal window of results.

**Comment by mjangda** [comment]
We end up piping the message "No apps found" (or a network error) to `less`, which is a bit awkward.

![2018-07-12 at 12 06 pm](https://user-images.githubusercontent.com/86105/42645479-22f8423e-85cc-11e8-90fb-d789a4fa9e1c.gif)

**Comment by mjangda** [comment]
Oh, my `$PAGER` is set to `less` without the `FRX` flags, which leads to the somewhat non-ideal experience.
