### ISSUE TITLE
Delete all option fails

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#149]
``` bash
$ vip sandbox delete --all

  error: missing required argument `site'
```

I think this worked previously… but checking back earlier versions I get the same error, so perhaps my recollection is faulty.

**Comment by joshbetz** [comment]
It has always required a site. This is from when we could spin up multiple sandbox containers per site. Technically it's still possible to create multiple sandbox containers with the API, but I think it's impossible if you only ever use the CLI.

I have been thinking about refactoring a bit to remove the edge cases around multiple sandboxes per site and make stop/delete always act on all containers per site.

**Comment by simonwheatley** [comment]
> It has always required a site. It's from when we could spin up multiple sandbox containers per site. 

Aha. I got it in my head it was for deleting all stopped containers across all sites. Closing.
