### ISSUE TITLE
Track version and OS

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#152]
Currently we bundle the version and the OS into the User Agent string, for tracking purposes. To help us understand the environment of our installed userbase, we should track the CLI version and the user OS separately. 

Perhaps put the OS in `browserplatform` and the version in `browserfamilyversion`?

**Comment by mjangda** [comment]
Will need to look into the innards of Tracks to see how it handles these properties (i.e. are they accepted as-is if passed in or are they generated?)
