### ISSUE TITLE
Delete `jetpack_options` after import, before cache flush

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-cli#155]

**Comment by david-binda** [comment]
@joshbetz @mjangda could we attempt to preserve already connected jetpack in case we are re-importing SQL to a site which has already been connected? I'm really not sure how does that play with Jetpack Start.

**Comment by mjangda** [comment]
@david-binda That's definitely the route we need to take; we have a thread on veetoop2 chatting about this.
