### ISSUE TITLE
Explain using double dashes for the run command

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#161]
From here:

> TL;DR: It's easiest to always use a double dash before the command you want to run.

Without the double dash, commands with arguments don't work. Given that this is the case, we should give people good examples.

Currently we don't reveal this critical tip to users in the command help:

``` bash
$ vip sandbox run --help

  Usage: run [options] <site> <command...>

  Run a wp-cli command on a sandbox container

  Options:

    -h, --help      output usage information
    --skip-confirm  Run the command without asking for confirmation
```

Adding something in the description seems a baseline, but is there anything else we can do to help our users here?

**Comment by philipjohn** [comment]
Is there any reason why the command can't do this for us by default?

I've been running into "Too many positional arguments" errors with all sorts of commands so I've just resorted to logging into a sandbox container instead to get things done.

**Comment by joshbetz** [comment]
> Is there any reason why the command can't do this for us by default?

That was my original idea, but unfortunately I don't think it's possible with Commander.js, so it wouldn't be a simple change.
