### ISSUE TITLE
Support sync on app with multiple environments with same environment_name

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-cli#161]
An app can have N environments of a given `environment_name` (say `develop`), but currently the `sync` command will grab the first one that matches instead of prompting the user to specify:

https://github.com/Automattic/vip/blob/c2502af7bf4533440e5f91c70774112d360d3af8/src/lib/cli/command.js#L215

These envs can be further distinguished by their `name`, or by having the user choose.

**Comment by mjangda** [comment]
This is fixed now.
