### ISSUE TITLE
Help for subcommands

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-cli#162]
Currently when you pass the `-h` param, you get the help for all top level commands, not specific help for a subcommand:

```
$ vip -h
  Usage: vip [options] [command]

  Commands:
    app      List and modify your VIP Go apps
    help     Display help
    logout   Logout from your current session
    sync     Sync production to a development environment
    version  Display version

  Options:
    -h, --help     Output usage information
    -v, --version  Output the version number

$ vip app -h
  Usage: vip [options] [command]

  Commands:
    app      List and modify your VIP Go apps
    help     Display help
    logout   Logout from your current session
    sync     Sync production to a development environment
    version  Display version

  Options:
    -h, --help     Output usage information
    -v, --version  Output the version number
```

**Comment by elazzabi** [comment]
After digging into this, to get help for subcommands, you actually need to use: `vip app help`. Passing `-h` or `--help` always prints the top level help

**Comment by nickdaugherty** [comment]
Since `-h` and `--help` are so common (and supported at the top level), we should still figure out how to get them working on subcommands, otherwise it's a confusing and disjointed experience.

@scottsweb recently shared this post about creating great CLI tools (from Heroku), and consistent / predictable help is number 1:

https://medium.com/@jdxcode/12-factor-cli-apps-dd3c227a0e46
