### ISSUE TITLE
Purify the output to allow piping

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#164]
I'd like to be able to pipe the output particularly from the `run` command to other commands, to loop over sites and perform operations. 

Example: I tried piping the JSON output of a WP CLI command into `jq` with the aspiration of looping over all the sites in a multisite and connecting Jetpack on them all:

``` bash
$ vip sandbox run example.go-vip.co --skip-confirm -- wp site list --fields=domain,path --format=json | jq '.[].domain'
parse error: Invalid numeric literal at line 1, column 8
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14)
```

**Comment by simonwheatley** [comment]
Perhaps related to #117?

**Comment by joshbetz** [comment]
I think dupe of #157?

**Comment by simonwheatley** [comment]
Aha. Yes, I think so. Closing.
