### ISSUE TITLE
Should `run` delete its container?

### ISSUE THREAD

**Issue by ethitter** [Automattic/vip-cli#165]
I ran a bunch of `run` commands to clear caches tonight, and periodically needed to delete sandboxes as I was triggering the warning about having more than five. Should we automatically delete the container created when using `run`?

**Comment by joshbetz** [comment]
Probably not by default, but we could add an option to do it.

If we try to run two commands in a row, you have to wait for the container to stop and then start again right now, which is kind of sub-optimal. If you had to wait for the container to delete and then be created again, it would make this worse.

**Comment by joshbetz** [comment]
@ethitter maybe instead of running things like this on a sandbox, we'd trigger them on the new wp-cli containers. Thoughts?

**Comment by ethitter** [comment]
Yeah, I think that makes the most sense. There's no technical reason to run these from a sandbox, and not tying up my sandbox for something like this is a nice bonus.
