### ISSUE TITLE
Using `wp export` with run command

### ISSUE THREAD

**Issue by philipjohn** [Automattic/vip-cli#170]
Running `wp export` with the `run` command doesn't seem to work well because we don't seem to have the export files. 

Example command:
`wp export --dir=/tmp/ --skip_comments --start_date=2017-03-11 --end_date=2017-04-10 --post_type=post`

Presumably, as the command runs inside the container, it's the `/tmp` directory in the container, rather than the host, where the export will be stored?

If this is the case, is there a way around that, to have the command store stuff on the host?

If not, could we disable commands like this with a notice that they need to be run manually by manually sandboxing?

**Comment by joshbetz** [comment]
Related: https://github.com/Automattic/vipd/pull/376

Until the above PR gets deployed, you can export to the wordpress directory or mu-plugins and access the files on the host.

**Comment by mjangda** [comment]
You can use `/home/dev-scripts/` as the `--dir` -- that directory is mounted from the host to the container.
