### ISSUE TITLE
replace debug with @automattic/vip-go

### ISSUE THREAD

**Issue by elazzabi** [Automattic/vip-cli#180]
This project is still using `debug`, can we replace it by the logger module in `@automattic/vip-go` ?

**Comment by mjangda** [comment]
`@automattic/vip-go` is more meant for hosted apps and we'd end up with a bunch of code we don't need.

If we want some consistency in the logging module, I think we should just use Winston directly instead?

**Comment by elazzabi** [comment]
yeah you're right. will close this (we can see later the use of `winston` or just keep `debug`)
