### ISSUE TITLE
Bulk Upgrades: if containers list is longer than terminal window, display breaks in odd ways

### ISSUE THREAD

**Issue by ethitter** [Automattic/vip-cli#190]
If the container list exceeds the terminal window height, the bottom portion that's within view behaves normally, while containers listed above the visible window are repeatedly output, rather than updating the existing output. Scrolling up and down gets strange, and it's hard to keep track of what the status of containers is.

**Comment by joshbetz** [comment]
Maybe if there are more than X containers in the batch, we should collapse the output to something like:

```
Upgrading N sites: X pending containers, Y upgrading containers, Z done containers (spinner)
```

**Comment by mjangda** [comment]
I do like seeing the detailed output on which containers are doing what. Could group things by site and list all the containers in a single cell?
