### ISSUE TITLE
Sanitise imported databases

### ISSUE THREAD

**Issue by philipjohn** [Automattic/vip-cli#197]
It would be useful to have a command that could be run following a new database import which would sanitise the database, removing any data that could cause issues, such as Jetpack options.

**Comment by philipjohn** [comment]
I've made a start in https://github.com/Automattic/vip-cli/tree/add/db-sanitise-command but I'm not quite sure how to handle the list of tables at the moment.

**Comment by ethitter** [comment]
There's a P2 post about doing this within `vipd`, so that we could back up certain options. If that approach pans out, the CLI will just need to queue some host actions.

**Comment by joshbetz** [comment]
There is another, related issue to validate imports in vip-cli before we start them. https://github.com/Automattic/vip-cli/issues/41

As @ethitter mentions, the sanitization itself will probably happen automatically via VIPd.

**Comment by joshbetz** [comment]
Closing favor of #41
