### ISSUE TITLE
vip files: Add s3 streaming importer

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-cli#201]
Port over @mdbitz's existing s3 streaming script.

**Comment by joshbetz** [comment]
As part of this, I think it would be good to refactor the upload function to take a file stream so we can pipe local uploads or remote uploads to the same function and not duplicate the upload logic.

https://github.com/Automattic/vip-cli/blob/master/src/lib/import.js#L4

**Comment by nickdaugherty** [comment]
I started some related work in this PR: https://github.com/Automattic/vip-cli/pull/121
