### ISSUE TITLE
Fix vip sandbox delete documentation

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-cli#215]
`vip sandbox delete --all` doesn't work. We need to use `vip sandbox purge` instead.

```
$ vip sandbox delete --help
  Usage: delete [options] <site>
  Delete existing sandbox
  Options:
    -h, --help  output usage information
    --all  Delete all stopped sandbox containers
$ vip sandbox delete --all 
  error: missing required argument `site'
```

**Comment by simonwheatley** [comment]
Could we alias `vip sandbox delete --all` to `vip sandbox purge`?

**Comment by joshbetz** [comment]
> Could we alias vip sandbox delete --all to vip sandbox purge?

Yeah, I was thinking the same. I can look into it.
