### ISSUE TITLE
Support roles greater than 2

### ISSUE THREAD

**Issue by ethitter** [Automattic/vip-cli#224]
Currently, only users with role `1` or `2` are supported, even if other roles may have the necessary API access to use commands such as `sandbox`. This is handled in https://github.com/Automattic/vip-cli/blob/cafbf8738a033d32d92f37c19ef050f2c4bf03bf/src/bin/vip.js: the variable `is_vip` is used to restrict access to all commands save `login` and `logout`. Now that other roles have access to some of the "internal" commands, we need a more-robust approach.

**Comment by joshbetz** [comment]
Good call. Since we have the currentUserCan functions in the vip-js-sdk library, we should use those instead of hard coding this.
