### ISSUE TITLE
`site upgrade` gets "stuck" after batch completes

### ISSUE THREAD

**Issue by ethitter** [Automattic/vip-cli#232]
During the 4.8.1 upgrade, after a batch completed, the CLI continued to refresh the completed table, but never exited or proceeded to the next batch. I had to interrupt after each batch.

**Comment by joshbetz** [comment]
Related: https://github.com/Automattic/vip-cli/pull/193

**Comment by ethitter** [comment]
Definitely related, but worth noting that this also happened to me on sites that only had running web containers.

**Comment by mjangda** [comment]
The problem:

```
$ vip api GET /container_types/1
{
    "status": "success",
    "result": 1,
    "data": [
        {
            "container_type_id": 1,
            "container_type_name": "Web Container",
            "active": 1
        }
    ]
}
```

and the value of `defaultStack` is:

```
var defaultStack = res.body.data[0].software_stack_name;
```

**Comment by joshbetz** [comment]
Related: https://github.com/Automattic/vip-go-api/commit/56d071c661dc59d994ba4413f1f861aab8779e7e

**Comment by mjangda** [comment]
@joshbetz I think the best option here is probably to switch to `/site_type_allocations` and use that. We probably will need to account for the different site and container types.
