### ISSUE TITLE
`site upgrade` does not support all filters provided by the `upgrade_wp` endpoint

### ISSUE THREAD

**Issue by ethitter** [Automattic/vip-cli#233]
Filters such as `client_id` are not supported.

**Comment by joshbetz** [comment]
`client_id` is called `client`. I guess we should either change it to client_id, or maybe do a search similar to how we handle site IDs now, where you can pass a name or ID.

https://github.com/Automattic/vip-cli/blob/master/src/bin/vip-site.js#L15

**Comment by ethitter** [comment]
Ah ha! The Field Guide mislead me, so I'll update that. It currently indicates that the command accepts all filters that the API endpoint supports.
