### ISSUE TITLE
WP CLI: Add subshell interface

### ISSUE THREAD

**Issue by elazzabi** [Automattic/vip-cli#259]
Adds support for a subshell experience where user can run a batch of commands without specifying the `app` and `env` each time.

Example
```
vip wp --app=123 --env=abc
> wp post list
COMMAND OUTPUT
> wp option get home
COMMAND OUTPUT
...
```

**Comment by nickdaugherty** [comment]
Going to bump this back to the v3 Epic

**Comment by elazzabi** [comment]
this was fixed by https://github.com/Automattic/vip/pull/280
