### ISSUE TITLE
Detect and Handle Unauthenticated Requests

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-cli#271]
When an API request is made that comes back unauthenticated, we need to transparently handle that by intercepting the program's flow to display a relevant error.

We can optionally start the auth flow too, though I wonder if it makes more sense to exit with an error then prompt them to run `vip login`.

Currently when a token is invalid or you are otherwise unauthenticated, the request runs then you get an error like this:

```
App some-random-app does not exist
```

**Comment by nickdaugherty** [comment]
I believe this was fixed with https://github.com/Automattic/vip/pull/272, right @elazzabi ?

**Comment by elazzabi** [comment]
yep this was fixed. Thank you for spotting 🙌 . Will close this then
