### ISSUE TITLE
Switch to CircleCI

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-cli#274]
Generally moving everything there.

**Comment by mjangda** [comment]
Only thing we can't move is the Windows tests.

**Comment by nickdaugherty** [comment]
Is that because CircleCI doesn't support it, or requires a different plan / licensing?

**Comment by mjangda** [comment]
Yeah, Circle only supports Linux and Mac.

**Comment by nickdaugherty** [comment]
Bummer.
