### ISSUE TITLE
tabtab prompt breaking Homebrew installation

### ISSUE THREAD

**Issue by tomjn** [Automattic/vip-cli#29]
While creating a homebrew formula for vip-cli I ran into an issue, here's the formula for testing:

`vip-cli.rb`:
```
require "language/node"

class VipCli < Formula
  desc "CLI Tools for WordPress.com VIP"
  homepage "https://github.com/Automattic/vip-cli"
  head "https://github.com/Automattic/vip-cli.git"

  depends_on "node"

  def install
    system "npm", "install", *Language::Node.std_npm_install_args(libexec), "wpvip-cli"
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    system "vip -v"
  end
end
```

Specifically, tabtab in the postinstall script, asks a question, causing homebrew to abort and assume failure

**Comment by joshbetz** [comment]
Tabtab isn't supposed to prompt, but the `--auto` flag appears to be broken. If we fix that, it should fix this as well.

**Comment by joshbetz** [comment]
https://github.com/mklabs/node-tabtab/issues/28
