### ISSUE TITLE
Fatals when running wp shell cause exit with no indication of error

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#290]
A fatal error in <code>wp shell</code> causes it to exit without any indication of an error:

```
$ vip --app 103 --env staging -- wp shell
Entering WP-CLI shell mode for staging on test-03 (103)
wp> poop()

[no response + exit]
```

We may want to consider setting <code>display_errors</code> to allow fatals?

**Comment by nickdaugherty** [comment]
cc @darthhexx - is displaying PHP errors when running remote WP CLI commands something we want to consider?

**Comment by nickdaugherty** [comment]
@simonwheatley I say we punt this to the v4...

**Comment by simonwheatley** [comment]
Fine with me, @nickdaugherty

**Comment by darthhexx** [comment]
The only concern that comes to mind is _leaky_ error messages :)

**Comment by mjangda** [comment]
WP 5.2 throws a new error thanks to the Fatal Error handling. That covers things for us here.
