### ISSUE TITLE
There's no cursor in the pseudo shell

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#291]
I find the lack of a cursor to indicate my focus is unnerving, is there anything we can do about this? 😰

**Comment by nickdaugherty** [comment]
It looks to me that `chalk` (which colors the prompt) is somehow interfering...investigating...

**Comment by nickdaugherty** [comment]
This will be fixed by https://github.com/Automattic/vip/pull/297

**Comment by nickdaugherty** [comment]
Fixed by https://github.com/Automattic/vip/pull/297
