### ISSUE TITLE
Help and Version commands on a WP command display the VIP CLI help and version

### ISSUE THREAD

**Issue by dchymko** [Automattic/vip-cli#293]
We probably want the ability for a user to be able to access the wp cli help (outside of the subshell help)

## Steps to reproduce
`vip --app=68 -- help`
`vip --app=68 -- version`

It appears that you can bypass the default help/version command parsing in the argv library. However, this prevents access to the help and version in the VIP CLI.
https://github.com/Automattic/vip/blob/master/src/lib/cli/command.js#L39
`const options = this.parse( argv, { help: false, version: false } );`

**Comment by elazzabi** [comment]
looks like `help`, `-h` and `--help` display the help screen, I wanted to see if we can configure this, i.e. displaying help only if we pass `-h` or `--help` but looks like it's an all or nothing flag...

Not sure how can we go around this, or if we need to use another package with more flexibility. Something like [commander](https://www.npmjs.com/package/commander)

Edit: less space too

- args (currently used): 31.5kb minified ([bundlephobia](https://bundlephobia.com/result?p=args@5.0.1))
- commander: 10.1kb minified ([bundlephobia](https://bundlephobia.com/result?p=commander@2.19.0))

**Comment by elazzabi** [comment]
Fixed by https://github.com/Automattic/vip/pull/295
