### ISSUE TITLE
Prompt for optional backup before command on production sites

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-cli#298]
On commands that modify data, a pre-command backup is a good idea. We can prompt users to optionally create a new backup before running commands.

We'll need to decide on the exact criteria for triggering the prompt, based on environment and the command being run.

We'll also need some API components to allow triggering the backup and to get a notification when the backup finishes.

**Comment by mjangda** [comment]
May be better handled as a flag (e.g. `--take-backup`).

Punt from v4 for now as this is very high complexity (needs Parker component, plus have to wait with status updates).
