### ISSUE TITLE
Naming things is hard: vgo or viggo or vipgo? 

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#299]
I didn't spot this at the time, but now we have `viggo` and `vgo`? 

I see a few issues:

* `viggo` looks like a typo… should it have been `vipgo`?
* `viggo` sounds like `vgo`

I think we should revisit the naming to have better clarity and differentiation.

**Comment by mjangda** [comment]
I thought the `viggo` suggestion was a joke -- not something we'd actually ship :)

**Comment by mjangda** [comment]
Changed in #291

**Comment by mjangda** [comment]
I'm fine with just sticking with `goop` or something more descriptive like `vipsupport`
