### ISSUE TITLE
Add: Copy db command

### ISSUE THREAD

**Issue by philipjohn** [Automattic/vip-cli#30]
`vip copy-db` - copies a database from one Go site to another.

This would replace the 11-14 individual commands needed at the moment with one single CLI command.

E.g. `vip copy-db 226 258` copies the DB from site ID 226 to site ID 258 and runs the relevant WP CLI commands to update the DB and run search/replace where needed.

**Comment by joshbetz** [comment]
We're going to do this via vipd. Should hopefully be ready to go after the Platform meetup in June.
