### ISSUE TITLE
WP-CLI: Quoted string value for parameter with spaces misinterpreted

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#309]
```
$ wp post list --posts_per_page=5 --meta_key=byline --meta_compare="NOT EXISTS" 
Error: Too many positional arguments: EXISTS"
```

Ref: https://github.com/wp-cli/wp-cli/issues/1928

via a client 🙂

**Comment by nickdaugherty** [comment]
Have some code for this that works locally, need to work out something on prod still.

**Comment by nickdaugherty** [comment]
This was fixed by https://github.com/Automattic/vip/pull/310 and a change to the runner.
