### ISSUE TITLE
Support sync to local environments

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/vip-cli#314]
In 91890-z, in discussions around data sync, the possibility to run a data sync to a local environment was discussed. I'm not sure how feasible this is, but if I could `vip sync` to a local environment in the same way I can sync to another VIP Go environment, it would be pretty handy. 

This might be in the works with providing easier exports, client dashboard functionality, etc, but wanted to flag here for visibility!

**Comment by mjangda** [comment]
Yep, definitely something we'd like to add 👍
