### ISSUE TITLE
Tracks: opt-out

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-cli#315]
We need a way for users to opt-out of Tracks via a direct command.

**Comment by nickdaugherty** [comment]
We should consider rolling this into a `config` command, as there are other configs we'll need to support, such as proxies.

**Comment by mjangda** [comment]
@mjangda to scope out specific of what's needed here.

Likely need to send a Tracks event and also stop sending future events.

**Comment by simonwheatley** [comment]
Related enquiry and discussion: https://wp.me/p4qSXL-37l
