### ISSUE TITLE
Use the primary domain, not the native domain

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#32]
In various places, the CLI tool shows a confirmation dialog including a line `Primary Domain:`, but the domain shown seems to be the native domain:

https://github.com/Automattic/vip-cli/blob/c32e29277fe13cc548e700157194ba99ecaa801b/src/bin/vip.js#L119

and

https://github.com/Automattic/vip-cli/blob/c32e29277fe13cc548e700157194ba99ecaa801b/src/src/utils.js#L121

**Comment by joshbetz** [comment]
Looks like this has since been fixed
