### ISSUE TITLE
Publish v1.4

### ISSUE THREAD

**Issue by mjangda** [Automattic/vip-cli#321]
Let's get it live for everyone

**Comment by nickdaugherty** [comment]
We already used `1.4.0` as a `next` release, so we'll need to tag this release as `1.4.1`.

**Comment by mjangda** [comment]
I think we can just change the dist-tag to `latest` when publishing? https://docs.npmjs.com/cli/dist-tag

**Comment by nickdaugherty** [comment]
This has been completed.
