### ISSUE TITLE
WP CLI: Add option to assume yes in prompts

### ISSUE THREAD

**Issue by dchymko** [Automattic/vip-cli#346]
## Description
When running commands, it is sometimes desirable to have any prompts assume a 'yes' response rather than stopping the flow for input. 

For example: piping command output to a file against a production environment (it will always confirm yes this action first). Since there is no way to bypass the prompt, it is:
- written into the piped output
- not displayed to the user and appears as if the command isn't doing anything. You can still press `y` to confirm but this is not an idea flow.

Note, this is only for prompts from the `vip` command, not on the wp commands themselves.

Example:
`vip -y @my-site.production -- wp term list category --format=csv > /tmp/category.csv`

**Comment by tomjn** [comment]
+1 to this, the prompt that asks if you're sure you want to run the command prevents me from doing a lot of automation using the `vip` command

**Comment by joshbetz** [comment]
Fixed by #353
