### ISSUE TITLE
Add progress indicator to running wp cli commands

### ISSUE THREAD

**Issue by dchymko** [Automattic/vip-cli#347]
Add an animated (or other type of "progress") indicator when running wp-cli command to signal to the user that the command is doing something.

This should be added to both traditional commands as well as the shell version. It also must be excluded from any output if the command is being piped to a file, etc.

**Comment by simonwheatley** [comment]
I'm going to close this to avoid creating issues we're not tackling immediately. Our client teams will remind us of the requirement for this if they need it :)
