### ISSUE TITLE
WP CLI: Interactive commands in subshell "hang" after first prompt

### ISSUE THREAD

**Issue by dchymko** [Automattic/vip-cli#357]
## Description
Commands that have multiple prompts (called via --prompt) do not work as expected in the subshell

## Steps to reproduce
```
$ vip wp --app <site id>
Welcome to the WP CLI shell for the develop environment of develop (example.com)!
develop.develop:~$ wp user create --prompt
1/15 <user-login>: 
```
"hangs" at this point.

## Workaround
Call the command outside of the subshell
 `vip <@siteid>-- wp user create --prompt`

**Comment by dchymko** [comment]
I tried running ` wp user create --prompt` outside of the shell ( #357) and it it hangs after entering data for the first prompt. 
```
./dist/bin/vip-wp.js --app=1163 -- user create  --prompt
1/15 <user-login>: testuser
<hang>
```

It works as expected with the current VIP command

```
vip --app=1163 -- wp user create --prompt
1/15 <user-login>: testuser
2/15 <user-email>: email@domain.tld
...
```

**Comment by joshbetz** [comment]
Sounds like the second input hangs in general #464

**Comment by dchymko** [comment]
I don't think the two are related unfortunately. In 464, the CLI wasn't sending any data to the socket after the first command. In this case, the data is being sent but for some reason the output isn't coming back.

running `DEBUG=* ./dist/bin/vip-wp.js` was super helpful in seeing whats going on behind the scenes, (although the socket code is super chatty and outputs a lot of debug stuff!)
