### ISSUE TITLE
Return error for unregistered commands

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#37]
I moved the credentials file `/tmp/.vip-go-api` to simulate not being logged in, and a failing command returns an exit code of `0`. I think it should exit non-zero, so we can more easily detect failures from other scripts.

``` bash
$ mv /tmp/.vip-go-api /tmp/.vip-go-api.bk 
$ vip api GET /sites/123/somecommand
$ echo $?
0
```

**Comment by joshbetz** [comment]
@simonwheatley Yes, it's because the command is unregistered. We probably need to send a PR to  https://github.com/tj/commander.js/

**Comment by simonwheatley** [comment]
I also get it for registered commands which fail:

```
$ mv /tmp/.vip-go-api /tmp/.vip-go-api.bk 
$ vip db 87
$ echo $?
0
```

**Comment by joshbetz** [comment]
It's not registered if you're not authenticated.
