### ISSUE TITLE
VIP-CLI blocks user delete without reassign, but multisite doesn’t support the reassign parameter

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#381]
From a client developer via DMs:

> Trying to run `example.develop:~$ wp user delete 123 --network --yes` and I’m blocked with `Error: `wp user delete` must use a `--reassign` parameter to avoid accidental post deletion` and including the reassign param doesn’t work on mu `Error: Reassigning content to a different user is not supported on multisite.`and including the reassign param doesn’t work on mu `Error: Reassigning content to a different user is not supported on multisite.`

The WP-CLI error message for `($network && $reassign)` is in the WP-CLI source here:

https://github.com/wp-cli/entity-command/blob/master/src/User_Command.php#L269

Can we safely allow user deletion on multisite without the reassign parameter?

**Comment by trepmal** [comment]
Nudging. I don't think we should be blocking with an error since this makes it impossible to run this across a network. 
Core already has a confirmation prompt if the command is run without `--reassign`

**Comment by dchymko** [comment]
The fix for this has been deployed and tested:
```
vip @mytestmultisite -- wp user delete dctest                
--reassign parameter not passed. All associated posts will be deleted. Proceed? [y/n] y
Success: Removed user 38 from https://example.com.
```
