### ISSUE TITLE
Better token expiry messaging

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#398]
When the client's token expires in the VIP-CLI tool we have some suboptimal messaging. Here's an example.

```
> vip wp @example-develop.go-vip.co
App example-develop does not exist
                                                                                                                                                                          
> vip wp @123
Error: Resource not found

> vipbox example-develop.go-vip.co
Invalid or expired token. Please login with `vipgo login`
```

A few things here:

* Can we make a more friendly message than `Error: Resource not found`, e.g. jump straight to the token expiry message?
* We shouldn't be referencing `vipgo login`, that's not the command name
* There is no `vip login` command, I think we should be referencing simply `vip` as the command to run?

Props @justnorris

**Comment by elazzabi** [comment]
Probably the used version is old. The new version gives this:

`Unauthorized: You are unauthorized to perform this request, please logout with `vip logout` then try again.`

**Comment by pyronaur** [comment]
It was the newest version at the time ;)

**Comment by simonwheatley** [comment]
Just spotted the `vipbox` command on the last command 🤦‍♂️ Closing as `wontfix` (?) for now.
