### ISSUE TITLE
Data question: Which method are people using to run WP-CLI commands?

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-cli#414]
I'd like to know how popular each of the methods of running WP-CLI commands is, e.g. "via pseudo-shell" and "via direct command". Can we add a property to all `vip_cli_wpcli_*` Tracks events which tracks this information, please?

Considerations:

* What to call the property: `command-run-via`?
* What to use for the property values: `pseudo-shell` and `direct` (or `shell)?

**Comment by elazzabi** [comment]
The proposal here is to use a flag containing `subshell` if it's the subshell mode. Or `normal` if it's the normal mode https://github.com/Automattic/vip/pull/447/files#diff-6bf77c3843951e6b92795206746dd5ceR182

**Comment by simonwheatley** [comment]
That gets my vote. Let's close this issue once that PR is merged.

**Comment by GaryJones** [comment]
That PR got merged, so closing.

FWIW, I happened to be re-reading the docs today, and found that pseudo-shell was a thing - I'd only been using direct command until then.
