### ISSUE TITLE
Calculate and send and send an offset for WP-CLI commands

### ISSUE THREAD

**Issue by elazzabi** [Automattic/vip-cli#418]
# Expected/Desired Behavior

When a command reconnects to the API, we should continue piping from the last point. We need to keep track of how much data we received and send an offset once reconnected to the API.

## Actual Behavior

We still don't have this.

**Comment by joshbetz** [comment]
We should be careful not to implement too much of the reconnect logic in the CLI in case we want to run CLI commands from other places in the future. Some potential options might be a browser extension or directly in the dashboard.

**Comment by joshbetz** [comment]
This is where the issue was originally created: 643 on the API

**Comment by elazzabi** [comment]
Fixed https://github.com/Automattic/vip/pull/420
