### ISSUE TITLE
Errors aren't showing in rollbar

### ISSUE THREAD

**Issue by elazzabi** [Automattic/vip-cli#421]
## Expected/Desired Behavior

After rolling rollup to get an overview of the error we get... It looks like we're not getting the full stack trace nor the full error.

We need to debug why is this happening and probably force logging what we need to log instead of relying on the default behavior (using `rollbar.error`)

## Actual Behavior

Errors aren't reported

**Comment by sjinks** [comment]
Closing because we have dropped Rollbar.
