### ISSUE TITLE
Interactive shell: second command failing

### ISSUE THREAD

**Issue by andrewfleming** [Automattic/vip-cli#464]
## Expected/Desired Behavior

Run more than one command via the interactive shell

## Actual Behavior

The second command run in an interactive shell hangs. 
There's zero output and the command needs to be killed `control + C`. This produces the output: `Command cancelled by user` but the shell remains in an unresponsive state. 
`Control + C` again and we exit the interactive shell.

## Steps to Reproduce the Problem

- Begin an interactive shell session using `vip @XXX.develop wp`
- Run an initial command doesn't matter which
- Run a second command, doesn't matter which, and the interactive shell hangs

## (Optional) Additional notes

```
vip --version
1.7.0
```

**Comment by dchymko** [comment]
Did some testing and couldn't reproduce in  `1.6.2` but I can reproduce in `1.7.0`. Will continue to investigate.
