### ISSUE TITLE
Automation via docker

### ISSUE THREAD

**Issue by brandoncamenisch** [Automattic/vip-cli#563]
I would like to run vip-cli in automation and/or through docker and there seem to be limited existing options to achieve that or they just aren't documented.

The first being I can't seem to find a variable or a config file that I can feed into the cli for an auth token and I'm forced to do it interactively.

The other issue I'm facing is a lot of the commands just show up blank such as `vip app list` works fine when using in a normal environment from the host machine but inside of docker it just returns nothing or a bunch of terminal jibberish.

My container so far is really simple but returns nothing for most commands when I run `vip ...`
```
FROM node:14.3.0
USER root
RUN npm i -g @automattic/vip
```
If I swap node with ubuntu I get terminal codes
```
FROM ubuntu
USER root
RUN npm i -g @automattic/vip
```
```
<E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><B4><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80>
<E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><B4><E2><94><80><E2><94><80><E2><94><80>
<E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80>
```
I hope I'm just missing some packages but is there a list of package requirements that the host machine would typically have which make the underlying commands work?

Or an existing docker container?
Or some other better alternative to interact with the go platform for automation purposes?

**Comment by brandoncamenisch** [comment]
closing this out... assume I'll never get a response. :shrug:

**Comment by mjangda** [comment]
@brandoncamenisch sorry we missed this. 

What types of automation are you looking to implement? There may be better ways to do them instead of going through the CLI.

**Comment by brandoncamenisch** [comment]
Oh thanks @mjangda :smile:  there are certain aspects of managing our go sites that we want to automate like data import/export and user management across many sites without opens zendesk tickets or doing manually. vip-cli seems to be engineered to run with an end user in mind instead of in automation. I wonder if there are better methods though like an api or something else that would allow us to admin sites in bulk.
