### ISSUE TITLE
Urecognized Arguments --format etc.

### ISSUE THREAD

**Issue by zgjimgjonbalaj** [Automattic/vip-cli#596]
Running a command with arguments such as `vip @maindomain.tld.staging-03 wp cmd sub-cmd --dry-run=false` results in the error message below. This is a user defined CLI command. VIP has confirmed these work on their end and this command works fine in OS X on my end as well, it does not function properly in Ubuntu 20.04/18.04 WSL 2 & Windows 10.

It seems as if the CLI app is not able to recognize or handle assoc arguments properly. Leads me to believe this is a platform specific issue in splitting\escaping command arguments.

```
The option "dry-run" is unknown. Did you mean the following one?
-v, --version  Output the version number
```

Ubuntu Details:
```
npm v6.14.6
nodejs v10.22.1
ubuntu 20.04 LTS / 18
Linux DESKTOP-0N1PKQU 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Windows Details:
```
npm v6.14.6
nodejs v10.22.1
Windows 10 Enterprise v2004 Build 19041.572
```

**Comment by elazzabi** [comment]
Howdy, thank you for reporting this! We'll take a look and get back to you as soon as possible 🙌

**Comment by markowsiak** [comment]
@zgjimgjonbalaj I am taking a look at this currently 👍 
Can you comment if you used any type of shell in Windows (via Git, ubuntu virtualization, etc..), or the standard Dos/Windows Shell?
Thanks you!

**Comment by zgjimgjonbalaj** [comment]
@markowsiak Thanks for looking into this. I used windows terminal preview the current version that's on MS Store and powershell as the console. I also tried CMD in Windows. For Ubuntu and WSL i used windows terminal again and zsh shell.

**Comment by gamebits** [comment]
@zgjimgjonbalaj In the example you provided:

```
vip @maindomain.tld.staging-03 wp cmd sub-cmd --dry-run=false
```

This command is missing the `--` which passes the `wp` command — see [our docs](https://docs.wpvip.com/technical-references/tools-for-site-management/wp-cli/#h-direct-commands) for more information.

Could you please try

```
vip @maindomain.tld.staging-03 -- wp cmd sub-cmd --dry-run=false
```

and let us know if you experience different results?

**Comment by zgjimgjonbalaj** [comment]
@gamebits 
![image](https://user-images.githubusercontent.com/60440190/101676782-7dd60d80-3a10-11eb-9661-acb22e1b72e7.png)

**Comment by zgjimgjonbalaj** [comment]
@gamebits @markowsiak 
![image](https://user-images.githubusercontent.com/60440190/101677188-1076ac80-3a11-11eb-8110-09ceefc3a35f.png)
![image](https://user-images.githubusercontent.com/60440190/101677227-1ff5f580-3a11-11eb-93bb-a11d43881c2f.png)

**Comment by zgjimgjonbalaj** [comment]
@gamebits @markowsiak 

### **Subcommands Available**
![image](https://user-images.githubusercontent.com/60440190/101677582-9692f300-3a11-11eb-993f-d86c31be7ff4.png)

### **Without Arguments**
![image](https://user-images.githubusercontent.com/60440190/101677609-a1e61e80-3a11-11eb-84a0-2a62c4b3fdf8.png)

### **With Arguments**
![image](https://user-images.githubusercontent.com/60440190/101677636-ac081d00-3a11-11eb-8b0c-cf0e209fa5d6.png)

### **Function Definition**
![image](https://user-images.githubusercontent.com/60440190/101677687-bfb38380-3a11-11eb-83a1-e47312684edd.png)

**Comment by zgjimgjonbalaj** [comment]
Additional example 

![image](https://user-images.githubusercontent.com/60440190/101679136-c17e4680-3a13-11eb-8918-3c03170f77fa.png)

**Comment by gamebits** [comment]
I'm no longer in a position to test this, so I don't know if the issue is still occurring, but perhaps parentheticals would allow the parameter to be passed successfully:

```
vip @foreignpolicy-com.staging-04 -- (wp fp list-tags --format=csv)
```
