### ISSUE TITLE
Docker and automation

### ISSUE THREAD

**Issue by bcamenisch** [Automattic/vip-cli#613]
A while back I opened [this issue](https://github.com/Automattic/vip/issues/563) which I closed out and was unresolved. A similar issue exists [here](https://github.com/Automattic/vip/issues/336) which has some similarities to what I've experienced when running the cli both in and outside of docker.

There are some other issues as well which may just be inherent to how wp cli is written as a whole. Such as this trickery below where we just want to loop through some users to run a command but end up having to generate an entire file beforehand so it doesn't fail or bork the terminal
 :confused: 
```
#!/bin/sh

# Run vip command to init with token
vip

# Create file for users which we're going to generate via a USERS_FILE and make executable
touch /tmp/users.sh && chmod +x /tmp/users.sh

# Create tmp users shell file with env vars
IFS=","
while read user_login user_email display_name role
do
  echo "vip $VIPGO_ENV -- wp user create $user_login $user_email --role=$role --send-email --display_name='$display_name'" >> /tmp/users.sh
done < $USERS_FILE

# Execute users
. /tmp/users.sh
```
:facepalm: right...
---
## Expected/Desired Behavior
We've a dire need to automate some administrative actions (preferably wp cli) across all of our go sites and need a tool that's consistent and reliably portable so that engineers and automation systems can perform the same actions easily. 

Some examples of what I mean could include:
- Administer a user account across all sites
- Administer content or run a across all sites
-  Running custom wp-cli commands on all sites
- etc.

Is this the best tool for the job or is there something else we could do that's already available or better suited?

## Reproduce
Our current docker image is built like this. If you run the cli side by side comparing this with outside of docker it doesn't match up at all. Is this environment configured wrong and if so what's the preferred environment instead? There' s no technical reason I can think of that this wouldn't work the same as a generic terminal outside of docker other than the environment is perhaps incorrectly handled below.
```
FROM node:14.3.0
USER root
RUN npm i -g --unsafe-perm=true @automattic/vip
COPY ./bin/* /usr/local/bin/
ENTRYPOINT /bin/bash`
```

Like I mentioned our ultimate goal is to automate with something our engineers or an automation system can handle that's easy and reliable and currently the cli is forcing us to make our changes manually via the cli. That unfortunately is a huge waste of time and is error prone when compared to scripting and automating these actions. Because nobody wants to login to 50 or so sites to run the same commands.

If there's anymore information I can provide in regards LMK as this would put a huge smile on a lot of peoples faces.

cc: @aaronjorbin

**Comment by mjangda** [comment]
It seems like there's three separate issues/questions here:

1) VIP-CLI not working predictably in your Docker environment.

2) VIP-CLI doesn't make automation easy. I'm assuming this is largely because of the auth / token step? Or are there other things you've run into?

3) Is VIP-CLI the right tool for the automation work? The WP REST API comes to mind but I imagine wrangling tokens/auth across all your environments may be challenging. We also have a VIP API, which the VIP CLI actually talks to and which we'll be sharing more about soon (although not sure how easy it will be to use with our WP-CLI implementation but I'm sure it's a solvable problem :)). 

It might be easiest to set up a call to talk through these and figure out how we can make things work for y'all. I'll reach out to set this up.

**Comment by bcamenisch** [comment]
Summed up exactly thanks. Our primary goal is automation and IaC where we can. So, we're mostly looking to solve that. If vip cli isn't the right candidate that's probably fine if there's alternatives. If there's an api reveal soon that could be even better depending on what's available with it.

A call sounds great. I'll see what I can find out on my end to setup.

**Comment by mjangda** [comment]
To programmatically define the token for the CLI, you can add a file called `~/.config/configstore/vip-go-cli.json` with the following:

```
{
	"vip-go-cli": "<YOUR_CLI_TOKEN_FROM_THE_DASHBOARD>"
}
```

You should now be able to run `vip app list` or any other authenticated commands.
