### ISSUE TITLE
More granular sandbox container list

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-cli#62]
We currently only show the first sandbox container per site. It helps that we now show the number of containers, but it doesn't give the state of each. We need to figure out the best view for this considering that we want to keep the list as condensed as possible.

We could show the number of containers/site/state. Something like:

```
┌────┬─────────────────┬─────────┬───────┐
│ ID │ Site Name       │ State   │ Count │
├────┼─────────────────┼─────────┼───────┤
│ 59 │ v2.joshbetz.com │ stopped │ 2     │
├────┼─────────────────┼─────────┼───────┤
│ 59 │ v2.joshbetz.com │ running │ 1     │
└────┴─────────────────┴─────────┴───────┘
```

Then, do we want the stop/delete/pause actions to effect all containers for a site by default instead of requiring the `--all` parameter?

**Comment by nickdaugherty** [comment]
I think that if you are listing sandboxes, you should just get a list of _all_ of them, rather than trying to collapse stuff down and hide info.

**Comment by joshbetz** [comment]
@nickdaugherty One of the problems with that is you can no longer use site names to manage containers. I like being able to use site names because they're easier to remember and the commands can all use consistent arguments. Most people will never need more than 1 container per site (and for those that do, it will be in the extreme minority) so I think we should optimize for that.

**Comment by nickdaugherty** [comment]
If everybody only ever has 1 container per site, then it's NBD if we list them out separately in the table - b/c they'll still only ever see 1 entry per site.

Then the 'power users' who may be running extra containers and want to know about them with a 'list' command are still supported too.

**Comment by joshbetz** [comment]
> If everybody only ever has 1 container per site, then it's NBD if we list them out separately in the table - b/c they'll still only ever see 1 entry per site.

Well it's a big deal because listing them all also requires listing container names and stopping/starting with container names instead of site names.

**Comment by simonwheatley** [comment]
I like that people can use site names too. I'm assuming any domain mapped to a site could be used?

How about:

* One container per row when listing
* Allow a container name column, but default to not showing it (so there could be multiple rows per site with no differentiation between them, if the container name col isn't showing)
* Keep the `--all` parameter for stop/delete/pause
* If trying to stop more than one container and the site name has been specified instead of the container and there's no `--all`, refuse and prompt the user to use container name

**Comment by joshbetz** [comment]
@simonwheatley yeah, something like that could work.
