### ISSUE TITLE
npm install fails with permission denied during keytar

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-cli#71]
Running sudo npm install -g @automattic/vip ends with:

```
prebuild-install WARN install EACCES: permission denied, access '/Users/nickdaugherty/.npm'
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@automattic/vip/node_modules/keytar/build'
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/@automattic/vip/node_modules/keytar
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@4.2.1 (node_modules/@automattic/vip/node_modules/keytar):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@4.2.1 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by joshbetz** [comment]
Are you sure `npm install` failed completely or it just skipped keytar? It says it's skipping the optional dependency, which is expected in some cases. If this is interrupting installation completely, that's not expected.

**Comment by joshbetz** [comment]
Oh, I'm pretty sure this is related to `sudo`. We can't use sudo to install the CLI. If you run into permissions issues, it's best to follow the advice here https://docs.npmjs.com/getting-started/fixing-npm-permissions

We may want to check the current user and bail in preinstall for root.
