### ISSUE TITLE
Add `vip cli <site> <command>` back

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-cli#77]
It will run a command and pipe stdout and stderr back to you. Would be useful for automating WP-CLI runs across sites.

**Comment by joshbetz** [comment]
Maybe call it `vip sandbox run`?

**Comment by joshbetz** [comment]
We should detect errors in the exit code of the script so the container doesn't stop if there was a typo in the supplied command, for example.

**Comment by mjangda** [comment]
This was implemented.
