### ISSUE TITLE
`vip sandbox start` switches to root user

### ISSUE THREAD

**Issue by philipjohn** [Automattic/vip-cli#84]
When using `vip sandbox start` I find I'm switched to the root user, and have to `exit` to return to `vipdev` to use the VIP CLI again.

> vipdev@philpeter.dev.dfw.vipv2.net: vip sandbox start 253
> Warning: There are more than 5 total sandbox containers on this host. Consider deleting some unused ones with `vip sandbox delete <site>`
> Waiting for sandbox to start...
> Waiting for sandbox to start...
> Waiting for sandbox to start...
> Waiting for sandbox to start...
> Waiting for sandbox to start...
> Waiting for sandbox to start...
> Waiting for sandbox to start...
> Waiting for sandbox to start...
> Waiting for sandbox to start...
> Waiting for sandbox to start...
> Waiting for sandbox to start...
> Waiting for sandbox to start...
> root@somevip-com-developgo-vipco_web_dev_0004:/chroot/var/www# vip sandbox delete 75
> bash: vip: command not found
> root@somevip-com-developgo-vipco_web_dev_0004:/chroot/var/www# vip sandbox list
> bash: vip: command not found
> root@somevip-com-developgo-vipco_web_dev_0004:/chroot/var/www# exit
> exit
> vipdev@philpeter.dev.dfw.vipv2.net:

**Comment by simonwheatley** [comment]
This is by design; the command drops you into the sandbox container at the command line, ready for you to tail the log, run a WP CLI command, etc.
