### ISSUE TITLE
Compile to a single binary

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-cli#90]
It turns out npm install is not great. It would be helpful to compile the CLI to a single binary so we can offer an alternative way to install it.

https://github.com/pmq20/node-packer

We should explore a fully compiled version, i.e. including V8 and maybe just building the JavaScript to a single file. In the first case, node wouldn’t even need to be installed to run it. That could become a big download and may be unnecessary though.

**Comment by simonwheatley** [comment]
From @tomjn:

> Homebrew might help for MacOS/Linux, I set up a brew tap a while ago for [various] stuff

**Comment by joshbetz** [comment]
I think Homebrew typically does something similar to npm -- downloads the source code and compiles it. I'd want to provide an installer that downloads pre-compiled binaries. If we offered a desktop app (maybe an electron menu-bar app?), we could bundle the CLI as well and auto-updates of the desktop app could also update the CLI.

**Comment by tomjn** [comment]
Actually it's easier to do precompiled binaries with homebrew than to compile, both are possible

**Comment by tomjn** [comment]
https://github.com/Automattic/homebrew-tap/blob/master/viphash.rb#L5

You give it a URL to download the file, and a checksum so it can verify its integrity

**Comment by tomjn** [comment]
Here's the cloudup cli using npm https://github.com/Automattic/homebrew-tap/blob/master/cloudup-cli.rb
