### ISSUE TITLE
Current user check (not root)

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-cli#91]
Don't allow the CLI to be installed as root because it will cause problems down the line.

**Comment by simonwheatley** [comment]
Maybe addresses https://github.com/Automattic/vip/issues/71 ?

**Comment by mjangda** [comment]
I think we can solve this with documentation for now; doing it in code feels messy and likely to cause other problems.

@joshbetz can you log what the problems with installing using sudo / root are?

**Comment by joshbetz** [comment]
The two problems I've seen are:

1. From #71:

```
prebuild-install WARN install EACCES: permission denied, access '/Users/nickdaugherty/.npm'
```

2. It install successfully, but not in a directory in the current user's PATH, so `vip` doesn't work.

**Comment by joshbetz** [comment]
I've been pointing people to https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by joshbetz** [comment]
@simonwheatley are you able to help wrangle some docs for this? I'm happy to help with the language if necessary. I'm assuming we'll have a doc in the VIP documentation. Anywhere else though?

**Comment by joshbetz** [comment]
https://vip.wordpress.com/documentation/vip-go/vip-cli/

**Comment by simonwheatley** [comment]
@joshbetz Yes, I can look at this.

**Comment by simonwheatley** [comment]
Is there no way we can throw an error during installation? I am fairly concerned that people will just plough through quickly and not notice documentation 😐

**Comment by simonwheatley** [comment]
Are there common issues we can spot when the code is running, or some kind of check we could build into `vip -v`?

**Comment by joshbetz** [comment]
It’s messy partially because root is a Unix thing, but we really need cross platform support. I think we can do it eventually, but ideally we can ship with just docs because I have a feeling this could get fairly involved.

**Comment by mjangda** [comment]
Closing; covered by docs for now. We can revisit if it's a commonly reported problem.
