### ISSUE TITLE
dev-env regression in v2.3.1

### ISSUE THREAD

**Issue by dawnerd** [Automattic/vip-cli#912]
Hey all, got a notice to upgrade to 2.3.1 from 2.3.0. After upgrading I only get 'unable to find user www-data: no matching entries in passwd file' when running start. Downgrading to 2.3.0 allows the project to start again.

I'm on a Macbook w/ M1 Max, Docker desktop 4.1.1, npm 7.6.3, node v15.12.0

Would be glad to help debug.

**Comment by ksattiraju614** [comment]
We are seeing same issue when trying to run the local set up after upgrading to 2.5.0

unable to find user www-data: no matching entries in passwd file
ERROR ==> unable to find user www-data: no matching entries in passwd file 

Im on Mac Docker Desktop 4.1.1 node v14.18

**Comment by chrisjimenez** [comment]
We're also running into the same issue when we upgraded to 2.5.0. I'm using a MacBook Pro running macOS 12.0.1(Monterey), Docker Desktop 4.2.0, node v14.18.1, npm v6.14.15
