### ISSUE TITLE
dev-env create using wrong WordPress image tag

### ISSUE THREAD

**Issue by ross-mulcahy** [Automattic/vip-cli#984]
## Expected/Desired Behavior

Expected behavior

Environment yml file should target correct WordPress image for WordPress 5.9/5.9.1 when using dev-env create

## Actual Behavior

.lando.yml has incorrectly formatted tag for WordPress 5.9 or 5.9.1, it currently is formatted like this:

image: ghcr.io/automattic/vip-container-images/wordpress:5.9   →  5.9.1

and should be 

image: ghcr.io/automattic/vip-container-images/wordpress:5.9.1

## Steps to Reproduce the Problem

Using VIP-CLI v2.9.1, Node v14.16.0, darwin 21.3.0

1. $ vip @1234 dev-env create
1. Select WordPress version 5.9   →  5.9.1
1. $ vip @1234 dev-env start

Response is "ERROR: for wordpress  invalid tag format"

![Screenshot 2022-03-03 at 16 59 02](https://user-images.githubusercontent.com/8986112/156778842-35b4f263-eae3-4da1-a579-0ec2b80cd8c1.png)

![Screenshot 2022-03-04 at 13 30 11](https://user-images.githubusercontent.com/8986112/156772089-6ed5faca-e1f4-4bce-b5b2-6ccbfe9c3f2c.png)

**Comment by ross-mulcahy** [comment]
Looks like this PR is addressing the issue: https://github.com/Automattic/vip/pull/980

**Comment by jesse-greathouse** [comment]
Thank you for bringing this up. The newest version of the VIP CLI: 2.9.2 has the remedy for this problem. Please update the CLI with NPM.

We appreciate so much your help and willingness to report these issues. Thank you.
